### ISSUE TITLE
How to use osc

### ISSUE THREAD

**Issue by renaudwiser** [rasmuskreiner/OSCVideo#2]
Hello Rasmus. I am very interested in using your programme to help me use multiple videos in a show. 
I am a choreographer and have just started learning about osc so I don't quite understand how to use the command to run you program. If I have a video file (let's call it video1.mp4) in the videos folder on the Pi (/home/pi/videos), what would be the osc message to type in Qlab to get it to play. Similarly what would be the message to write to simply quit the program. 

I hope you can help. Many thanks

**Comment by rasmuskreiner** [comment]
Hi!

Since you are new to OSC I’ll just clear some basics. The first part of a message is the address – sometimes referred to as calling a method. Everything that follows is considered as arguments. Multiple arguments are separated by whitespace. Arguments are data fed to the method.

There are two ways of playing the file you specified:

  1.  Using the play method. This is simply that would be: /play 1 “/home/pi/videos/video1.mp4”
     *   This is calling the /play method with the arguments 1 and “/home/pi/videos/video1.mp4”. The player slot 1 and the absolute file path of the video file respectively.
  2.  This way requires two OSC-messages. First load the file into a player slot, and then tell that slot to play. This would be these two messages:
     *   /load 1 1 “/home/pi/videos/video1.mp4” (the arguments being: playerNumber, layer (currently not used), absolute file path)
     *   /play 1 (tell slot 1 to play)

The latter approach is most efficient since it instantiates and preloads the video before playback. The first approach will (depending on the files properties, and the capabilities of the Raspberry Pi) have a bit of delay once called. This is because it has to instantiate and preload before the playback can happen.

Keep in mind that there are 10 slots available so you could do the preloading of a second file in an empty slot while another slot is playing.

Hope the above makes sense.

Fra: renaudwiser ***@***.***>
Dato: onsdag, 19. maj 2021 kl. 17.34
Til: rasmuskreiner/OSCVideo ***@***.***>
Cc: Subscribed ***@***.***>
Emne: [rasmuskreiner/OSCVideo] How to use osc (#2)

Hello Rasmus. I am very interested in using your programme to help me use multiple videos in a show.
I am a choreographer and have just started learning about osc so I don't quite understand how to use the command to run you program. If I have a video file (let's call it video1.mp4) in the videos folder on the Pi (/home/pi/videos), what would be the osc message to type in Qlab to get it to play. Similarly what would be the message to write to simply quit the program.

I hope you can help. Many thanks

**Comment by renaudwiser** [comment]
Dear Rasmus,


Thank you for you fast answer. It makes a lot more sense now. 
I am however still experiencing some issues and I would be very grateful if you could answer the below:

- When I launch OSCVideo on the Pi, is it normal to only have a black screen or should I see any information before sending any messages from Qlab?
- While I have followed the message exemples you have sent me, nothing is happening at the moment, I have found the IP address of the pi but do not have a specific port for it to specify in Qlab. Does it matter and would it be why nothing is happening?  If so, how do I find this information. 

Many thanks for taking the time to get back to me. Much appreciated.


Warm wishes,


Renaud Wiser

**Comment by rasmuskreiner** [comment]
Dear Renaud,

- It is normal behavior that start OSCVideo will black out the screen. If you want to reveal the desktop send the command /background_off to the PI. /background_on will turn it black once again.
- The port matters a lot. A little analogy: If you consider network as the postal service. Then the Mac-address would be the GPS-coordinates, the IP-address would be the actual address and the port would be the person to receive the letter. So it does matter. OSCVideo uses port 53003 use that in QLab, and see if you get any results. You can try to test with the this command: /testImage_on '1080'.

If the above does work then the network setting are working properly. If you are still not able to play your own file, then it will either be a codec issue or that the filepath is wrong. To test the codec you can open a terminal and type in the following: "omxplayer /home/pi/videos/video1.mp4" (replace with your own file path, and without the quotation marks).

**Comment by renaudwiser** [comment]
Dear Rasmus,
Thank you very much for your response. Qlab is now communicating with the pi and I am able to send a range of commands. Still some small issues that I struggle with but most likely because of how I write the commands and I should be able to figure it out. Cheers and best wishes.
